#!/bin/zsh
# Since Sublime is fucking insane and can't handle symlinks for the User
# directory, we'll need to manually copy stuff over.

rm -rf "~/Library/Application Support/Sublime Text 2/Packages/User"
cp -R "$DOTFILES/sublime2/User" "~/Library/Application Support/Sublime Text 2/Packages/User"
