#!/bin/zsh
# Setup a machine for Sublime Text 2
set -x

# symlink settings in
sublime_dir="~/Library/Application Support/Sublime Text 2/Packages"
mv "$sublime_dir/User" "$sublime_dir/User.backup"
ln -s "$DOTFILES/sublime2/User" "$sublime_dir"

# Grab the Soda theme
git clone https://github.com/buymeasoda/soda-theme/ "$sublime_dir/Theme - Soda"
